name: joint_purchases
description: Application for calculating joint purchases.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  bloc: ^8.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^2.0.0
  intl: ^0.17.0
  local_storage_meetings_api:
    path: packages/local_storage_meetings_api
  meetings_api:
    path: packages/meetings_api
  meetings_repository:
    path: packages/meetings_repository
  share_plus: ^4.0.10
  very_good_analysis: ^3.0.1

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mockingjay: ^0.2.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  generate: true